---
- name: Setup common config
  hosts: all:!jumpbox
  gather_facts: false
  become: yes
  tags:
    - stage5

  roles:
    - 3tier-common

- name: Setup frontend load-balancer tier
  hosts: frontends
  gather_facts: false
  become: yes
  tags:
    - stage5
    - frontends

  roles:
    - 3tier-frontend-tier

- name: Setup app tier
  hosts: apps
  gather_facts: false
  become: yes
  tags:
    - stage5
    - apps

  roles:
    - 3tier-app-tier

- name: Setup database tier
  hosts: appdbs
  become: yes
  tags:
    - stage5
    - databases

  roles:
    - 3tier-geerlingguy.postgresql
...
